version: "3.9"

services:
  service-a:
    build: ./service-a
    container_name: service_a
    networks:
      - mynetwork

  service-b:
    build: ./service-b
    container_name: service_b
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service-a
      - service-b
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
