version: '3.9'

services:
  php:
    image: php:8.2-fpm
    container_name: php-app
    volumes:
      - ./app:/var/www/html
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx-web
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - "8080:80"
    networks:
      - webnet

networks:
  webnet:
