version: "3.9"
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - bridge-net

  db:
    build: ./db
    networks:
      - bridge-net

networks:
  bridge-net:
    driver: bridge
