version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_env_demo
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
