version: "3.9"

services:
  registry:
    image: registry:2
    container_name: private-registry
    restart: always
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: :5000
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
      - ./registry/config.yml:/etc/docker/registry/config.yml