version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:80"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
